version: '3'
services:

#  nodejs-example-service:
#    image: mellies/nodejs-example-service
#    container_name: nodejs-example-service
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "5000:3050"
#    environment
#    - NODE_ENV=production
#    links:
#      - mongodb-service
#    depends_on: 
#      - mongodb-service
  
  mongodb-service:
    image: tutum/mongodb
    container_name: mongodb-service
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
    - AUTH=no

  redis-service:
    image: redis
    container_name: redis-service
    ports:
      - "6379:6379"